# Generated by Django 5.2.4 on 2025-07-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0024_alter_competence_id_alter_education_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Competence",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Information",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
