# Generated by Django 4.2.23 on 2025-07-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0025_delete_competence_delete_education_delete_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("github_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome class e.g., fab fa-html5",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma-separated tags like Python, Django",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
